# Generated by Django 2.1.2 on 2018-11-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(max_length=50)),
                ('phone_number', models.BigIntegerField()),
                ('residence', models.CharField(max_length=50)),
                ('cleared', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('session_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_slug', models.SlugField(default=models.CharField(max_length=50))),
                ('size', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('brand', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('U', 'unisex')], max_length=2)),
                ('available', models.BooleanField(default=True)),
                ('rating', models.IntegerField(default=0)),
                ('tags', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='customerorder',
            name='shoes_ordered',
            field=models.ManyToManyField(to='shop.Shoe'),
        ),
    ]
