# Generated by Django 2.1.2 on 2018-11-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20181112_1420'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoeImages',
            new_name='ShoeImage',
        ),
        migrations.AlterField(
            model_name='shoe',
            name='name_slug',
            field=models.SlugField(help_text='how do you want the url to appear'),
        ),
    ]
