# Generated by Django 2.1.2 on 2018-11-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20181112_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400)),
                ('question_slug', models.SlugField()),
                ('answer', models.TextField()),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
    ]
