# Generated by Django 2.1.2 on 2018-11-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_slug',
            field=models.SlugField(blank=True),
        ),
        migrations.RemoveField(
            model_name='faq',
            name='tag',
        ),
        migrations.AlterField(
            model_name='shoe',
            name='name_slug',
            field=models.SlugField(blank=True, help_text="how do you want the url to appear don't edit. An automatio one is generated from name"),
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='tags',
        ),
        migrations.AddField(
            model_name='faq',
            name='tag',
            field=models.ManyToManyField(to='shop.Tag'),
        ),
        migrations.AddField(
            model_name='shoe',
            name='tags',
            field=models.ManyToManyField(to='shop.Tag'),
        ),
    ]
