# Generated by Django 2.1.2 on 2018-11-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20181112_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerorder',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='question_slug',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='preferred_name',
            field=models.CharField(help_text='Enter the name you would like us to refer to you by', max_length=50),
        ),
    ]
