# Generated by Django 2.1.2 on 2018-11-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20181113_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='name_slug',
            new_name='slug',
        ),
    ]
