# Generated by Django 2.1.2 on 2018-11-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20181113_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoeimage',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
