# Generated by Django 2.1.2 on 2018-11-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_shoeimage_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='price',
            field=models.BigIntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='shoeimage',
            name='image',
            field=models.ImageField(help_text='please make sure the image is in a ratio of 16:9', upload_to='shoes/'),
        ),
        migrations.AlterField(
            model_name='shoeimage',
            name='main',
            field=models.BooleanField(default=False, help_text='Mark at-least one as main(important)'),
        ),
    ]
