# Generated by Django 2.1.2 on 2018-11-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20181114_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='for_shoe',
            field=models.BooleanField(default=True),
        ),
    ]
