# Generated by Django 2.1.5 on 2019-10-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_tag_for_shoe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoe',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='customerorder',
            name='total_amount',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='phone_number',
            field=models.CharField(help_text="Enter a valid Kenyan number starting with '07'", max_length=10),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='residence',
            field=models.CharField(help_text='Where would you like to get your order', max_length=50),
        ),
    ]
