# Generated by Django 2.1.5 on 2020-02-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20191017_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='total_amount',
        ),
    ]
